spring.cloud.config.enabled=false

# 2. Configuración de PostgreSQL (lee las variables del .env)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# 3. Configuración del servicio GestoPago (lee las variables del .env)
gestopago.auth.url=${GESTOPAGO_AUTH_URL}
gestopago.auth.id-distribuidor=${GESTOPAGO_AUTH_ID_DISTRIBUIDOR}
gestopago.auth.codigo-dispositivo=${GESTOPAGO_AUTH_CODIGO_DISPOSITIVO}
gestopago.auth.password=${GESTOPAGO_AUTH_PASSWORD}
gestopago.auth.api-key=${GESTOPAGO_AUTH_API_KEY:YSX1HpAFum4TpCecyFBxs4eIjAlbhKqK6fpcSQp8}

# 4. Tasa de sincronización diaria de productos (24 horas = 86400000 ms)
gestopago.productos.refresh-rate-ms=${GESTOPAGO_PRODUCTOS_REFRESH_RATE_MS:86400000}